### ISSUE TITLE
Feedback requested

### ISSUE THREAD

**Issue by juanshishido** [dlab-berkeley/introduction-to-pandas#3]
@pattyf, @deniederhut, @davclark, @jackspaceBerkeley, @jonstiles, @sbenthall

The [notebook](https://github.com/dlab-berkeley/introduction-to-pandas/blob/master/introduction-to-pandas.ipynb) for the intro to pandas workshop is almost ready to go, I think. I'd appreciate some feedback when you have time.

One specific thing I need help with is determining when we're dealing with methods, attributes, or properties.

Thanks!

**Comment by davclark** [comment]
Thanks for this @juanshishido! I think this is the kind of thing I _should_ be doing. 
1. D-Lab defaults:
   1. I think @deniederhut is onboard with python 3 being default. Your code all works fine on py3.
   2. I talked to our office of licensing and tech transfer. They like the 2-clause BSD license (you're using the MIT license). Also, school spririt, man! Go Bears!
2. Good choice of dataset. And good for using a non-crappy matplotlib style (defaults will change soon!).
3. The first time you use `.head()` consider mentioning that this is using fancy Jupyter (née IPython) features to do rich HTML display (instead of ascii text like you'd see in the terminal - but if they haven't seen the terminal, just explain that the notebook renders some objects into nice HTML). Students will see shortly later in the notebook how `pandas.Series` objects do _not_ render so nicely.
4. I'd start with [more "official" approaches to indexing](http://pandas.pydata.org/pandas-docs/stable/indexing.html). In particular,
   1. `my_df[:5]` and `my_df['colname']` index on different dimensions. This is confusing (and you introduced it for columns in code block 6), but provided because pandas cares about efficiency for the analyst in the moment, not the reader (or learner) of the code, and
   2. you actually introduce `.iloc[]` later in comparison to bare `[]`. I think you mean to explain the difference between `.loc[]` and `.iloc[]`. AFAICT `[]` with a slice behaves similarly to `.iloc[]`.
   3. [This is one of the reasons I don't like Pandas - the indexing system is an afterthought developed by a committee lacking a pythonic aesthetic.]
5. Your `.groupby()` example would be more efficient using the Series method `.value_counts()`. I include that in a notebook in a pull request. Your later uses of `groupby` are fully taking advantage of / need `groupby`.
6. The implicit string conversion where you are generating dates using integer multiplication was confusing to me. I suspect it will be confusing to the students who are keeping up. You could do explicit string conversion and concatenation, or at least explain what's going on.
7. Plotting multiple lines would be a nice extra bit. Just do it in the stupid overlay approach.

Great lesson!

**Comment by juanshishido** [comment]
Thanks for these great comments, @davclark! Really good suggestions. I'll take a closer look at the PR. Will likely incorporate everything you've mentioned. I want to make sure it's clear to readers/learnings.

**Comment by juanshishido** [comment]
Merged the pull request. Will make other suggested edits.

**Comment by pattyf** [comment]
Hi Juan,

Great tutorial, nice pace and tone. Good examples. Out of curiosity, but
not necessary, could add at the very end a plot that shows Poland
unemployment rate and adds a line for average unemployment rate for all
countries in the data set. Not sure if that would be a natural extension or
too much.
P.

Patty

On Fri, Sep 11, 2015 at 11:13 AM, Juan Shishido notifications@github.com
wrote:

> @pattyf https://github.com/pattyf, @deniederhut
> https://github.com/deniederhut, @davclark https://github.com/davclark,
> @jackspaceBerkeley https://github.com/jackspaceBerkeley, @jonstiles
> https://github.com/jonstiles, @sbenthall https://github.com/sbenthall
> 
> The notebook
> https://github.com/dlab-berkeley/introduction-to-pandas/blob/master/introduction-to-pandas.ipynb
> for the intro to pandas workshop is almost ready to go, I think. I'd
> appreciate some feedback when you have time.
> 
> One specific thing I need help with is determining when we're dealing with
> methods, attributes, or properties.
> 
> Thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dlab-berkeley/introduction-to-pandas/issues/3.

## 

Patty Frontiera
Academic Coordinator
D-Lab, _Supporting Data Intensive Social Science for All_
356 Barrows Hall, University of California Berkeley
http://dlab.berkeley.edu

**Comment by juanshishido** [comment]
Thanks for the comments and suggestion, @pattyf. I need to add a bit more to the end, e.g., multiple lines to the plot and show how to export data. I like the idea of adding the average unemployment rate across countries (reminding participants, of course, that there is missing data for some time periods). Finishing the workshop with plotting is nice because I can promote the upcoming workshop on Matplotlib.

**Comment by davclark** [comment]
I think @pattyf's suggestion is a great, specific example of the general "plot several lines" suggestion I made! You might demonstrate different style in this case (make the average bolder or so).

A nice exercise you could leave folks with is how to do imputation to get a better sense of the mean unemployment. You don't need to provide a "correct" answer, but one way would be to do something like EM:
1. Fill all NAs with mean of other values (or something sensible)
2. Repeat until changes get "small":
   1. Compute mean based on current country values
   2. Compute regression weights for "mean ~ country values"
   3. Update missing country values using current regression weights and current mean value

I don't promise, but I'm pretty sure that should converge

**Comment by juanshishido** [comment]
Great suggestion, @davclark! I hope to implement by the end of the week.

**Comment by deniederhut** [comment]
Looking good @juanshishido ! :+1:

**Comment by juanshishido** [comment]
Just realized that The Hacker Within has a [pandas talk](http://bids.berkeley.edu/events/hacker-within-pandas) the same day as the D-Lab workshop. Will try and go to that!

**Comment by juanshishido** [comment]
Did not incorporate EM. Perhaps in the next iteration. Closing issue; notebooks ready.
